# Generated by Django 4.1.7 on 2023-11-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.TextField(blank=True, choices=[('', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], null=True)),
                ('Phone', models.IntegerField()),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
