# Generated by Django 4.1.7 on 2023-11-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='UserId',
        ),
    ]
