# Generated by Django 4.1.7 on 2023-11-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_bookedslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.TextField(unique=True),
        ),
    ]
